### ISSUE TITLE
Variable naming is ambiguous

### ISSUE THREAD

**Issue by bingo65334** [teiid/kubernetes-service-catalog-client#11]
Hello，When I used the client, I found an issue that the parameter named serviceClass  is ambiguous in the function getClusterServicePlan . I think it should be servicePlan. What do you think?

public static String getClusterServicePlan(String baseUrl, String apiVersion, String authHeader,
            String serviceClass) {
        String url = baseUrl + "/apis/servicecatalog.k8s.io/"+apiVersion+"/clusterserviceplans/"+serviceClass;
        return executeGET(url, authHeader);
    }

**Comment by rareddy** [comment]
Sure looks like it, if you want create a issue and submit a patch I will accept it.

**Comment by bingo65334** [comment]
@rareddy Thank you for your prompt reply. Can I change the source code directly and submit it?
